-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
local HALL_PB = require("hall_pb")
module('sign_pb')


C_GETSIGNINFO_0X1060 = protobuf.Descriptor();
S_GETSIGNINFO_0X1060 = protobuf.Descriptor();
local S_GETSIGNINFO_0X1060_SIGN_INFO_FIELD = protobuf.FieldDescriptor();
C_SIGNIN_0X1061 = protobuf.Descriptor();
local C_SIGNIN_0X1061_SIGN_DAY_FIELD = protobuf.FieldDescriptor();
S_SIGNIN_0X1061 = protobuf.Descriptor();
local S_SIGNIN_0X1061_SIGN_INFO_FIELD = protobuf.FieldDescriptor();
S_ENABLESIGNNOTIFY_0X1062 = protobuf.Descriptor();

C_GETSIGNINFO_0X1060.name = "C_GetSignInfo_0x1060"
C_GETSIGNINFO_0X1060.full_name = ".C_GetSignInfo_0x1060"
C_GETSIGNINFO_0X1060.nested_types = {}
C_GETSIGNINFO_0X1060.enum_types = {}
C_GETSIGNINFO_0X1060.fields = {}
C_GETSIGNINFO_0X1060.is_extendable = false
C_GETSIGNINFO_0X1060.extensions = {}
S_GETSIGNINFO_0X1060_SIGN_INFO_FIELD.name = "sign_info"
S_GETSIGNINFO_0X1060_SIGN_INFO_FIELD.full_name = ".S_GetSignInfo_0x1060.sign_info"
S_GETSIGNINFO_0X1060_SIGN_INFO_FIELD.number = 1
S_GETSIGNINFO_0X1060_SIGN_INFO_FIELD.index = 0
S_GETSIGNINFO_0X1060_SIGN_INFO_FIELD.label = 2
S_GETSIGNINFO_0X1060_SIGN_INFO_FIELD.has_default_value = false
S_GETSIGNINFO_0X1060_SIGN_INFO_FIELD.default_value = nil
S_GETSIGNINFO_0X1060_SIGN_INFO_FIELD.message_type = HALL_PB.PROTOSIGNINFO
S_GETSIGNINFO_0X1060_SIGN_INFO_FIELD.type = 11
S_GETSIGNINFO_0X1060_SIGN_INFO_FIELD.cpp_type = 10

S_GETSIGNINFO_0X1060.name = "S_GetSignInfo_0x1060"
S_GETSIGNINFO_0X1060.full_name = ".S_GetSignInfo_0x1060"
S_GETSIGNINFO_0X1060.nested_types = {}
S_GETSIGNINFO_0X1060.enum_types = {}
S_GETSIGNINFO_0X1060.fields = {S_GETSIGNINFO_0X1060_SIGN_INFO_FIELD}
S_GETSIGNINFO_0X1060.is_extendable = false
S_GETSIGNINFO_0X1060.extensions = {}
C_SIGNIN_0X1061_SIGN_DAY_FIELD.name = "sign_day"
C_SIGNIN_0X1061_SIGN_DAY_FIELD.full_name = ".C_SignIn_0x1061.sign_day"
C_SIGNIN_0X1061_SIGN_DAY_FIELD.number = 1
C_SIGNIN_0X1061_SIGN_DAY_FIELD.index = 0
C_SIGNIN_0X1061_SIGN_DAY_FIELD.label = 2
C_SIGNIN_0X1061_SIGN_DAY_FIELD.has_default_value = false
C_SIGNIN_0X1061_SIGN_DAY_FIELD.default_value = 0
C_SIGNIN_0X1061_SIGN_DAY_FIELD.type = 5
C_SIGNIN_0X1061_SIGN_DAY_FIELD.cpp_type = 1

C_SIGNIN_0X1061.name = "C_SignIn_0x1061"
C_SIGNIN_0X1061.full_name = ".C_SignIn_0x1061"
C_SIGNIN_0X1061.nested_types = {}
C_SIGNIN_0X1061.enum_types = {}
C_SIGNIN_0X1061.fields = {C_SIGNIN_0X1061_SIGN_DAY_FIELD}
C_SIGNIN_0X1061.is_extendable = false
C_SIGNIN_0X1061.extensions = {}
S_SIGNIN_0X1061_SIGN_INFO_FIELD.name = "sign_info"
S_SIGNIN_0X1061_SIGN_INFO_FIELD.full_name = ".S_SignIn_0x1061.sign_info"
S_SIGNIN_0X1061_SIGN_INFO_FIELD.number = 1
S_SIGNIN_0X1061_SIGN_INFO_FIELD.index = 0
S_SIGNIN_0X1061_SIGN_INFO_FIELD.label = 2
S_SIGNIN_0X1061_SIGN_INFO_FIELD.has_default_value = false
S_SIGNIN_0X1061_SIGN_INFO_FIELD.default_value = nil
S_SIGNIN_0X1061_SIGN_INFO_FIELD.message_type = HALL_PB.PROTOSIGNINFO
S_SIGNIN_0X1061_SIGN_INFO_FIELD.type = 11
S_SIGNIN_0X1061_SIGN_INFO_FIELD.cpp_type = 10

S_SIGNIN_0X1061.name = "S_SignIn_0x1061"
S_SIGNIN_0X1061.full_name = ".S_SignIn_0x1061"
S_SIGNIN_0X1061.nested_types = {}
S_SIGNIN_0X1061.enum_types = {}
S_SIGNIN_0X1061.fields = {S_SIGNIN_0X1061_SIGN_INFO_FIELD}
S_SIGNIN_0X1061.is_extendable = false
S_SIGNIN_0X1061.extensions = {}
S_ENABLESIGNNOTIFY_0X1062.name = "S_EnableSignNotify_0x1062"
S_ENABLESIGNNOTIFY_0X1062.full_name = ".S_EnableSignNotify_0x1062"
S_ENABLESIGNNOTIFY_0X1062.nested_types = {}
S_ENABLESIGNNOTIFY_0X1062.enum_types = {}
S_ENABLESIGNNOTIFY_0X1062.fields = {}
S_ENABLESIGNNOTIFY_0X1062.is_extendable = false
S_ENABLESIGNNOTIFY_0X1062.extensions = {}

C_GetSignInfo_0x1060 = protobuf.Message(C_GETSIGNINFO_0X1060)
C_SignIn_0x1061 = protobuf.Message(C_SIGNIN_0X1061)
S_EnableSignNotify_0x1062 = protobuf.Message(S_ENABLESIGNNOTIFY_0X1062)
S_GetSignInfo_0x1060 = protobuf.Message(S_GETSIGNINFO_0X1060)
S_SignIn_0x1061 = protobuf.Message(S_SIGNIN_0X1061)

