//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PacketsT.proto
namespace CC.Runtime.PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"R_User_Login_0x8000")]
  public partial class R_User_Login_0x8000 : global::ProtoBuf.IExtensible
  {
    public R_User_Login_0x8000() {}
    
    private string _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _playerName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"T_User_Login_0x8000")]
  public partial class T_User_Login_0x8000 : global::ProtoBuf.IExtensible
  {
    public T_User_Login_0x8000() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"R_User_JoinGroup_0x8001")]
  public partial class R_User_JoinGroup_0x8001 : global::ProtoBuf.IExtensible
  {
    public R_User_JoinGroup_0x8001() {}
    
    private uint _groupType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint groupType
    {
      get { return _groupType; }
      set { _groupType = value; }
    }
    private uint _groupId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"groupId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint groupId
    {
      get { return _groupId; }
      set { _groupId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"T_User_JoinGroup_0x8001")]
  public partial class T_User_JoinGroup_0x8001 : global::ProtoBuf.IExtensible
  {
    public T_User_JoinGroup_0x8001() {}
    
    private uint _groupType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint groupType
    {
      get { return _groupType; }
      set { _groupType = value; }
    }
    private uint _groupId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"groupId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint groupId
    {
      get { return _groupId; }
      set { _groupId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"R_User_ChannelMsg_0x8002")]
  public partial class R_User_ChannelMsg_0x8002 : global::ProtoBuf.IExtensible
  {
    public R_User_ChannelMsg_0x8002() {}
    
    private uint _groupType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint groupType
    {
      get { return _groupType; }
      set { _groupType = value; }
    }
    private string _msg;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"T_User_ChannelMsg_0x8002")]
  public partial class T_User_ChannelMsg_0x8002 : global::ProtoBuf.IExtensible
  {
    public T_User_ChannelMsg_0x8002() {}
    
    private uint _groupType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint groupType
    {
      get { return _groupType; }
      set { _groupType = value; }
    }
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _msg;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"T_User_ChannelReturn_0x8003")]
  public partial class T_User_ChannelReturn_0x8003 : global::ProtoBuf.IExtensible
  {
    public T_User_ChannelReturn_0x8003() {}
    
    private uint _groupType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint groupType
    {
      get { return _groupType; }
      set { _groupType = value; }
    }
    private uint _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"R_User_PersonalMsg_0x8004")]
  public partial class R_User_PersonalMsg_0x8004 : global::ProtoBuf.IExtensible
  {
    public R_User_PersonalMsg_0x8004() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _msg;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"T_User_PersonalMsg_0x8004")]
  public partial class T_User_PersonalMsg_0x8004 : global::ProtoBuf.IExtensible
  {
    public T_User_PersonalMsg_0x8004() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _msg;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"T_User_PersonalReturn_0x8005")]
  public partial class T_User_PersonalReturn_0x8005 : global::ProtoBuf.IExtensible
  {
    public T_User_PersonalReturn_0x8005() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}